### ISSUE TITLE
elVeh Battery Attribute

### ISSUE THREAD

**Issue by graemebiggs** [itchannel/fordpass-ha#123]
It would be great to have the elVeh entity attributes broken out into their own entities. I have been unable to break out the battery fill level attribute using templates, which is really the main thing I am interested in with an EV.

**Comment by tobox** [comment]
Same problem here... I would love to monitor SoC, but I cannot find it in the current entities.

**Comment by colings** [comment]
This works for me.

`  - platform: template
    sensors:
      car_voltage:
        friendly_name: "Car Charge Level"
        value_template: "{{state_attr('sensor.fordpass_elVeh', 'Battery Fill Level')}}"
        unit_of_measurement: "%"`

**Comment by tobox** [comment]
Thanks for the hint, it works for me too. I was unaware that there were additional attributes "hidden" inside the elVeh entity. I am relatively new to Homeassistant...

**Comment by itchannel** [comment]
Thanks @colings for posting your template. I did think about expanding out the elveh attributes but it's a lot cleaner to just have them as extras and then users can just use a template where needed if you want individual sensors.

**Comment by Bert-R** [comment]
The same can be done for the remaining range. Note that the first character shows as uppercase in Lovelace, but in reality is lower case (`elVehDTE`):
```
- platform: template
  sensors:
    ford_remaining_range:
      entity_id: sensor.fordpass_elVeh
      unique_id: sensor_ford_remaining_range
      friendly_name: "Remaining range"
      value_template: "{{state_attr('sensor.fordpass_elVeh', 'elVehDTE')}}"
      unit_of_measurement: "km"
```

**Comment by OArndt** [comment]
Hey everyone, 
I just finished setting up my first HA-instance and wanted to add the aforementioned attributes to my UI.
However, I'm kinda lost. I tried adding this
```
  - platform: template
  - sensor:
      - name: "Battery charge level"
        friendly_name: "Car Charge Level"
        unique_id: sensor.ford_car_charge_level
        value_template: "{{state_attr('sensor.fordpass_elVeh', 'Battery Fill Level')}}"
        unit_of_measurement: "%"

      - name: "Remaining range"
        friendly_name: "Car remaining range"
        unique_id: sensor.ford_remaining_range
        state: "{{state_attr('sensor.fordpass_elVeh', 'elVehDTE')}}"
        unit_of_measurement: "km"
```
       
to my /config/configuration.yaml, but I just get an error saying 

> "bad indentation of a mapping entry at line 16, column 13:
>       - platform: template" 

and no new entity to add to my overview

What am I doing wrong?
Sorry if this is a noob question, but I'm kinda lost here...
Any help is really appreciated!
Thanks!

**Comment by tballarin** [comment]
@OArndt, you can test this code on your config/configuration.yaml

```
template:
  - sensor:
    - name: "Ford Remaining range"
      unique_id: sensor_ford_remaining_range
      state: "{{state_attr('sensor.fordpass_elVeh', 'elVehDTE')}}"
      unit_of_measurement: "km"
  - sensor:
    - name: "Ford Battery charge level"
      unique_id: sensor_ford_car_charge_level
      state: "{{state_attr('sensor.fordpass_elVeh', 'Battery Fill Level')}}"
      unit_of_measurement: "%"
```

**Comment by 7ooL** [comment]
I used this for an entity filter to know if the car was plugged in our not

```
binary_sensor:
 - platform: template
    sensors:
      ford_mache_plug_status:
        friendly_name: "Plug Status"
        value_template: "{{state_attr('sensor.fordpass_elVeh', 'Plug Status')}}"
        device_class: plug
        unique_id: ford_mache_plug_status
```
