### ISSUE TITLE
Using fordpass GPS position in HA proximity integration

### ISSUE THREAD

**Issue by ThePitaGyros** [itchannel/fordpass-ha#169]
Dear fordpass developers,

I wanted to use the device_tracker.fordpass_tracker or sensor.fordpass_gps in the HA proximity integration, but I only get "not set" as value.

Has anyone tried this besides me?

Here is my configuration.yaml snippet for the proximity integration:

```
proximity:
  fordpass:
    devices:
      - device_tracker.fordpass_tracker
    tolerance: 100
    unit_of_measurement: km
  fordgps:
    devices:
      - sensor.fordpass_gps
    tolerance: 100
    unit_of_measurement: km
```

Both values should work, but do not, despite having latitude and longitude as attributes (like the HA device tracker - which is working in the HA proximity integration).

Any ideas?
All the best, Pita.

**Comment by ThePitaGyros** [comment]
Found the solution:

The longitude and latitude values provided by the fordpass integration provide the values with single quotes. Those values cannot be parsed by the proximity integration.

If you use a template to construct a new entity that contains those values without quotes - everything works smoothly.

All the best, Pita.

**Comment by ppacher** [comment]
@ThePitaGyros could you share your configuration on how to get this to work with the proximity integration?

**Comment by ThePitaGyros** [comment]
Hello ppacher,

sure thing. Here is my approach:

When looking at the values in the entity device_tracker.fordpass_tracker (or sensor.fordpass_gps) you will find latitude and longitude state attributes enclosed in single quotes, like this:

```
latitude: '55.751244'
longitude: '37.618423'
gps_accuracy: 48
timestamp: 04-30-2022 14:17:52
```

Other device_trackers (like the one that comes with the Home Assistant mobile app) provide those state attributes without single quotes. Those attributes work with the proximity integration, but the fordpass_tracker does not.

So I used the [template integration](https://www.home-assistant.io/integrations/template/) to get rid of the single quotes and convert the string attributes to floats, like this...

```
template:
  - sensor:
      - name: "Ford Focus"
        state: >
          {{ states('device_tracker.fordpass_tracker') }}
        attributes:
          icon: >
            mdi:radar
          source_type: >
            gps
          latitude: >
            {{ state_attr('device_tracker.fordpass_tracker', 'latitude') | float }}
          longitude: >
            {{ state_attr('device_tracker.fordpass_tracker', 'longitude') | float }}
          gps_accuracy: >
            {{ state_attr('device_tracker.fordpass_tracker', 'gps_accuracy') | float }}
          timestamp: >
            {{ state_attr('device_tracker.fordpass_tracker', 'timestamp') }}
```

and now I had a new sensor which I could use in the proximity integration...
(please note that gps_accuracy and timestamp are not required for proximity integration, but I wanted to include them)

```
proximity:
  fordfocusfromhome:
    zone: Home
    devices:
      - sensor.ford_focus
    tolerance: 100
    unit_of_measurement: km
```

Have fun!
Pita.
