### ISSUE TITLE
Problem getting fordpass_tracker automation to trigger upon arrival to home zone

### ISSUE THREAD

**Issue by rtw819** [itchannel/fordpass-ha#256]
Looking at my truck arrival automation using the "fordpass_tracker".  It last triggered at the end of September last year.  While I do see the device fordpass_tracker entity successfully shifting between home, away, and one other custom zone that I have defined, however the "home arrival" automation has not triggered in quite some time.  My goal was to trigger one last update for the evening after the vehicle enters the home zone (assumedly would be parked, shut and locked) and after a delay (5 mins in this case) beyond entering the home zone will pull then current stats via a refresh action.
 
This automation had worked previously, but perhaps there's something obvious wrong with it you might be able to spot at a glance?  (VIN is redacted) Is there a better or more correct way to perform this activity?  Hoping a fix to this helps others down the road. Thanks in advance!

```
alias: FordPass Update after truck enters home Zone
description: >-
  This Automation calls the FordPass update action after a check for the truck
  location has transitioned to Home
trigger:
  - platform: geo_location
    source: "entity_id: device_tracker.fordpass_tracker"
    zone: zone.home
    event: enter
condition:
  - condition: state
    entity_id: device_tracker.fordpass_tracker
    state: home
action:
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: fordpass.refresh_status
    data:
      vin: 1FT6**************
mode: single
```

**Comment by itchannel** [comment]
This is an automation I use for testing which works fine on detecting the zone changes. Might help. 

```
alias: Ford Track test
description: ""
trigger:
  - platform: zone
    entity_id: device_tracker.fordpass_tracker_2
    zone: zone.home_2
    event: enter
  - platform: state
    entity_id:
      - device_tracker.fordpass_tracker_2
    from: home
    to: away
condition: []
action:
  - service: persistent_notification.create
    data:
      title: test
      message: test
mode: single
```

**Comment by rtw819** [comment]
Will give this a try and report back.  Thank you!!

**Comment by itchannel** [comment]
@rtw819 Did this work for you?

**Comment by rtw819** [comment]
> @rtw819 Did this work for you?

What you provided was **very** close to what I ended up implementing.  Thanks for the recommendation!  This now seems to be pretty reliable.  I also added a 5 minute delay after entering the home zone before kicking off the the refresh in an attempt to avoid false positives with my other automation that provides an indication/notification of unlocked doors, open doors, open windows, etc. on our second Ford.

Here's the full automation routine I ended up using for others that may be looking for ideas:
(Don't forget to update the VIN, and remove the _2 portion of the tracker name if you only have one vehicle in FordPass.)

```
alias: Ford2 Arrived Home
description: >-
  This Automation calls the FordPass update action after coming Home
trigger:
  - platform: zone
    entity_id: device_tracker.fordpass_tracker_2
    zone: zone.home
    event: enter
  - platform: state
    entity_id:
      - device_tracker.fordpass_tracker_2
    from: away
    to: home
condition: []
action:
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: fordpass.refresh_status
    data:
      vin: <VIN_REDACTED>
  - service: persistent_notification.create
    data:
      title: Ford2 arrived home
      message: Ford2 arrived home and FordPass update requested at {{ now() }}
      notification_id: car_arrival_notification
mode: single

```

Thanks again for all you do!
