### ISSUE TITLE
15 minute refresh not working?

### ISSUE THREAD

**Issue by magnetic157** [itchannel/fordpass-ha#279]
Hello,

I've noticed on my application even though it's set to 900 seconds, my API refresh only happens every 2 hours.  If I have the car plugged in (its a PHEV) it will refresh a lot more often (every 15-20 minutes), but as soon as it's done charging it goes back to 2 hour intervals.  You can see below where it stopped charging (around 1:30am).

I could create an automation to automatically pull the refresh every 15 minutes, but shouldn't this be doing it on it's own or no?

<img width="1418" alt="image" src="https://github.com/itchannel/fordpass-ha/assets/78054864/94528d07-cfd3-4f15-88cd-08b2c4e132c1">

<img width="371" alt="image" src="https://github.com/itchannel/fordpass-ha/assets/78054864/bb45092d-27b4-4305-9931-c2bf0fa6c385">

**Comment by itchannel** [comment]
Last refresh is when the fordpass API last polled the car for data not how often the integration has refreshed. 

By default the integration doesn't poll the car automatically to prevent battery drain so that value will only update if you either run the refresh_status service or when the car automatically updates the API. Which is usually only done if the car is running or charging.

**Comment by mikedhanson** [comment]
How do you run the refresh_status? I have some automations setup around this where I would like to auto lock my doors after n minutes but the problem is the integration has old data. Im thinking about refreshing the data before checking/running the automations

**Comment by mikedhanson** [comment]
![image](https://github.com/itchannel/fordpass-ha/assets/15201245/0178697b-df26-4e04-b267-c017b85b8a80)

refreshing through dev tools doesnt seem to work either.

**Comment by itchannel** [comment]
@mikedhanson So running "refresh_status" will poll the car and typically the data will be returned within 5mins depending on cell connection etc. However the update of the actual API data only happens on the set 900 second interval so if you want to create an automation that updates the data and then acts on it the best option is something like below:

```
description: ""
mode: single
trigger: []
condition: []
action:
  - service: fordpass.refresh_status
    data:
      vin: xxxxxxxxxx
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: fordpass.poll_api
    data: {}
  - if:
      - condition: state
        entity_id: lock.fordpass_doorlock
        state: unlocked
    then:
      - service: lock.lock
        data: {}
        target:
          entity_id: lock.fordpass_doorlock_2
```


The break down is 

1. Contact car to get updated status (Can take up to 10mins due to cell reception and having to wake the car from sleep)
2. Wait 5-10 mins before running the next step
3. Refresh integration manually outside of the normal 900 second refresh
4. Act on results e.g. lock the car if status is unlocked.
