### ISSUE TITLE
403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v5/MYVIN/status?lrdt=01-01-1970+00%3A00%3A00

### ISSUE THREAD

**Issue by philipgo** [itchannel/fordpass-ha#303]
Hello,

since today I get the error message "403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v5/MYVIN/status?lrdt=01-01-1970+00%3A00%3A00" 

I am on version 1.52

Thank you for your great work!

**Comment by AndreiGavriliu** [comment]
Also having the same issue. I enabled debugging and found the following info. maybe it helps

```
2023-10-09 13:24:23.726 DEBUG (MainThread) [custom_components.fordpass] 900
2023-10-09 13:24:23.727 DEBUG (MainThread) [custom_components.fordpass] username
2023-10-09 13:24:23.727 DEBUG (MainThread) [custom_components.fordpass] password
2023-10-09 13:24:23.727 DEBUG (MainThread) [custom_components.fordpass] region
2023-10-09 13:24:23.727 DEBUG (MainThread) [custom_components.fordpass] vin
2023-10-09 13:24:23.727 DEBUG (MainThread) [custom_components.fordpass] UK&Europe
2023-10-09 13:24:23.728 DEBUG (MainThread) [custom_components.fordpass.fordpass_new] /config/custom_components/fordpass/[REDACTED]_fordpass_token.txt
2023-10-09 13:24:23.733 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2023-10-09 13:24:24.221 WARNING (MainThread) [custom_components.fordpass] 403 Client Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v5/[REDACTED]/status?lrdt=01-01-1970+00%3A00%3A00
2023-10-09 13:24:24.222 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for [REDACTED]
2023-10-09 13:24:24.222 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for [REDACTED]
2023-10-09 13:24:24.222 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 0.493 seconds (success: False)
```

Cheers,
Andrei

**Comment by tobox** [comment]
Same for me (Germany) with a Mustang Mach-E. 

Telemetry data shows up properly in Android app.

**Comment by marwonn** [comment]
Same here:

Error: Forbidden for url: https://usapi.cv.ford.com/api/vehicles/v5/MYVIN/status?lrdt=01-01-1970+00%3A00%3A00"

**Comment by jblaze03** [comment]
> Can confirm, same issue (Canada)

+1

**Comment by serlinGi** [comment]
Same for me with my 2 cars.  Italy

**Comment by tonesto7** [comment]
I'm seeing the same :(

They've been working on releasing the new FordConnect API.  I wonder if they finally moved over  to it

**Comment by Fifty889** [comment]
+1
Germany

**Comment by sweidenbach** [comment]
+1
Germany (Mach E)
Already changed refresh_status from v2 to v5 due to 403 at 2023/09/15.

**Comment by dtx1990** [comment]
Same problem in italy

**Comment by jwfox5150** [comment]
Same issue here.

**Comment by bb12489** [comment]
Same issue here as well. 403 forbidden.

**Comment by mrgroen** [comment]
Same here...

**Comment by albamatti** [comment]
Same here in Holland

**Comment by csfreak** [comment]
I have confirmed that my Fordpass app has switched to the new api.autonomic.ai endpoint.  

I have found a working JS example of using the new API.
https://github.com/TA2k/ioBroker.ford/blob/master/main.js

Should provide a good start to the endpoints and the responses, especially if mitmproxy is not available.

**Comment by AlexW75** [comment]
Same here … Germany Ford Focus.

**Comment by virtualbitzz** [comment]
same here

**Comment by mojomojoman** [comment]
> I have confirmed that my Fordpass app has switched to the new api.autonomic.ai endpoint.
> 
> I have found a working JS example of using the new API. https://github.com/TA2k/ioBroker.ford/blob/master/main.js
> 
> Should provide a good start to the endpoints and the responses, especially if mitmproxy is not available.

eek. this is a major rewrite I think.  I was hoping I could hack it back into operation just changing the BASE_URL but looking at that other guys code its a lot more than that.  We're all gonna owe the dev a few beers for this rewrite.

Example:
```
  async updateVehicles() {
    await this.getAutonomToken();
    const statusArray = [
      // { path: "statusv2", url: "https://usapi.cv.ford.com/api/vehicles/v2/$vin/status", desc: "Current status v2 of the car" },
      // { path: "statususv4", url: "https://usapi.cv.ford.com/api/vehicles/v4/$vin/status", desc: "Current status v4 of the car" },
      // { path: "statususv5", url: "https://usapi.cv.ford.com/api/vehicles/v5/$vin/status", desc: "Current status v5 of the car" },
      // {
      //   path: "fuelrec",
      //   url: "https://api.mps.ford.com/api/fuel-consumption-info/v1/reports/fuel?vin=$vin",
      //   desc: "Fuel Record of the car",
      // },
      {
        path: "statusQuery",
        url: "https://api.autonomic.ai/v1beta/telemetry/sources/fordpass/vehicles/$vin:query",
        desc: "Current status via query of the car. Check your 12V battery regularly.",
      },
    ];
```
I really should learn python and api's one of these days but how long have I been saying that now. ;-)

**Comment by mharris1984** [comment]
Same for me.  One Ford vehicle in USA.  HA logs show the 403 forbidden starting at 3 AM UTC-7:00 (AZ Time) (10-11 hours ago)

**Comment by itchannel** [comment]
I am actively working on a new release to fix this. But there has been some considerable changes not just in the endpoint and token management but also the data now retrieved from the API. As you can see below I have now got it pulling back data again but there's some major bugs and rewrites I need to overcome first. 

Also worst possible time for me for these changes to be made :)

```
homeassistantstable  | 2023-10-10 *********** DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] {"updateTime":"2023-10-01**********","vehicleId":"*******58008857db1e","vin":"*************","metrics":{"alarmStatus":{"updateTime":"2023-09-24**********","oemCorrelationId":"38833","tags":{"ALARM_SOURCE":"UNKNOWN"},"value":"ARMED"},"acceleratorPedalPosition":{"updateTime":"2023-09-24**********","oemCorrelationId":"38833","value":0.0},"batteryStateOfCharge":{"updateTime":"2023-09-24**********","oemCorrelationId":"38833","value":37.0,"vehicleBattery":"PRIMARY_BATTERY"},"batteryVoltage":{"updateTime":"2023-09-24T**********","oemCorrelationId":"38833","value":12.1875,"vehicleBattery":"PRIMARY_BATTERY"}
```

**Comment by jwfox5150** [comment]
> I am actively working on a new release to fix this. But there has been some considerable changes not just in the endpoint and token management but also the data now retrieved from the API. As you can see below I have now got it pulling back data again but there's some major bugs and rewrites I need to overcome first.
> 
> Also worst possible time for me for these changes to be made :)
> 
> ```
> homeassistantstable  | 2023-10-10 *********** DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] {"updateTime":"2023-10-01**********","vehicleId":"*******58008857db1e","vin":"*************","metrics":{"alarmStatus":{"updateTime":"2023-09-24**********","oemCorrelationId":"38833","tags":{"ALARM_SOURCE":"UNKNOWN"},"value":"ARMED"},"acceleratorPedalPosition":{"updateTime":"2023-09-24**********","oemCorrelationId":"38833","value":0.0},"batteryStateOfCharge":{"updateTime":"2023-09-24**********","oemCorrelationId":"38833","value":37.0,"vehicleBattery":"PRIMARY_BATTERY"},"batteryVoltage":{"updateTime":"2023-09-24T**********","oemCorrelationId":"38833","value":12.1875,"vehicleBattery":"PRIMARY_BATTERY"}
> ```

We appreciate you! Thank you for your work on this.

**Comment by mojomojoman** [comment]
wow. RIP all my sensor templates.  no more elveh i guess. HVB status will be reported under "fuel" status i guess.  and whats up with "acceleratorPedalPosition" is that a thing they are really logging?  I would expect that from an OBD2 but not from the api. lol

**Comment by itchannel** [comment]
This is currently what I see for my vehicle, I don't know if someone with a electric vehicle will get the extra data like elveh. Hoping this isn't the only endpoint as it no longer supports window positions either. 

![image](https://github.com/itchannel/fordpass-ha/assets/5840973/09ab6e65-da5f-4532-affe-8bbaa9c314bb)

**Comment by SquidBytes** [comment]
Considering the massive changes, I closed my Pull Request with the EV specific sensors.
As far as further development related to EV features, what's the best way to work with you? I wasn't sure if my pull request was the right approach.

**Comment by itchannel** [comment]
> Considering the massive changes, I closed my Pull Request with the EV specific sensors. As far as further development related to EV features, what's the best way to work with you? I wasn't sure if my pull request was the right approach.

Pull request is fine, honestly I've been massively busy with work so this project has sort of taken a back burner whilst it's been working ok. Once I get these massive changes implemented/fixed this week then I'm happy to work with you to increase the electric vehicle features if/how they are now supported in the new API.

**Comment by SquidBytes** [comment]
> > Considering the massive changes, I closed my Pull Request with the EV specific sensors. As far as further development related to EV features, what's the best way to work with you? I wasn't sure if my pull request was the right approach.
> 
> Pull request is fine, honestly I've been massively busy with work so this project has sort of taken a back burner whilst it's been working ok. Once I get these massive changes implemented/fixed this week then I'm happy to work with you to increase the electric vehicle features if/how they are now supported in the new API.

Understandable. My week is crazy also. I'll wait to grab the new release and start seeing if I can find what may be missing from EV, or what can be added.

**Comment by virtualbitzz** [comment]
> eek. this is a major rewrite I think. I was hoping I could hack it back into operation just changing the BASE_URL but looking at that other guys code its a lot more than that. We're all gonna owe the dev a few beers for this rewrite.

Sorry man, sponsorship coming your way. If I could code worth a dam I'd volunteer my time

> ![image](https://user-images.githubusercontent.com/5840973/273701101-25c10836-bb8f-4a17-9bae-1c75b1bddf85.png) Current progress. A lot of data is missing in the new vehicle status API but there's also some cool new info like transmission status.
> 
> I'll try and have a beta later today which will be full of bugs but should restore basic functionality until I can work through all the new endpoints and json variables.

Sweet, thanks for getting on this so quick! Sponsorship coming your way

**Comment by BGetchell** [comment]
Sponsor sent! Thanks for working it so quick.

**Comment by mojomojoman** [comment]
> This is currently what I see for my vehicle, I don't know if someone with a electric vehicle will get the extra data like elveh. Hoping this isn't the only endpoint as it no longer supports window positions either.
> 
> ![image](https://user-images.githubusercontent.com/5840973/273702990-09ab6e65-da5f-4532-affe-8bbaa9c314bb.png)

I've got an EV (Mustang Mach-E).  I can test for you if that beta is live.  Or if you wanna give me a quick tutorial of how to poll the API direct in python I could feed you back what I'm seeing.  I don't code python. I know a lot of PowerShell but that's probably not gonna help me here.  The data I used to get back for the HVB was a bunch of attribs shoved into one sensor which was hard to utilize in HASS in a lot of cards so I had a bunch of custom template sensors to split it out before.

e.g. from configuration.yaml
```
template:
  - sensor:
      - name: "Mach-E Battery charge"
        unique_id: sensor_fordpass_elveh_battery
        state: "{{state_attr('sensor.fordpass_elVeh', 'Battery Fill Level')}}"
        unit_of_measurement: "%"
        device_class: battery
  - sensor:
      - name: "Mach-E Charging Status"
        unique_id: sensor_fordpass_elveh_chstatus
        state: "{% if (is_state_attr('sensor.fordpass_elveh','Charging Status','NotReady')) %} Idle {% else %} {{state_attr('sensor.fordpass_elveh','Charging Status')}} {{ state_attr('sensor.fordpass_elveh','Plug Status') }} {% endif %}"
        icon: mdi:ev-station
  - sensor:
      - name: "Mach-E Charge Start Time"
        unique_id: sensor_fordpass_elveh_chstart
        state: "{{ strptime(state_attr('sensor.fordpass_elveh','Charge Start Time'),'%m-%d-%Y %H:%M:%S').strftime('%-m/%d %H:%M')  }}"
        icon: mdi:clock
  - sensor:
      - name: "Mach-E Charge Complete ETA"
        unique_id: sensor_fordpass_elveh_chend
        state: "{{ strptime(state_attr('sensor.fordpass_elveh','Charge End Time'),'%m-%d-%Y %H:%M:%S').strftime('%-m/%d %H:%M') }}"
        icon: mdi:clock
  - sensor:
      - name: "Mach-E Frunk"
        unique_id: sensor_fordpass_doorstatus_frunk
        state: "{{ (state_attr('sensor.fordpass_doorstatus', 'hoodDoor'))  }}"
        icon: mdi:car-door
  - sensor:
      - name: "Mach-E Driver Door"
        unique_id: sensor_fordpass_doorstatus_driver
        state: "{{ (state_attr('sensor.fordpass_doorstatus', 'driverDoor'))  }}"
        icon: mdi:car-door
```
And this one which isn't a real sensor value but a derived one. 
```
  - sensor:
      - name: "Mach-E Battery Max Range"
        unique_id: sensor_fordpass_elveh_maxrange
        state: "{{ ((states('sensor.mach_e_range') | int) + (states('sensor.mach_e_range') | int) / (states('sensor.mach_e_battery_charge') | int) * (100 - (states('sensor.mach_e_battery_charge') | int))) | round()  }}"
        unit_of_measurement: "mi"
        device_class: distance
        icon: mdi:gauge
```
Purpose of that is to calculate what the car would currently think my max range would be if I had 100% battery.  The actual expected range in Mi/Km of the remaining battery is not a static value in Ford EVs.  The car is constantly updating the expected Miles per Kwh based on recent drives, outside temp, and/or some kind of secret sauce algorithm that they don't reveal.  I don't know how much you know about EVs but the range estimates are practically wild guesses.  If the weather is perfect and I don't need heat or AC and I'm doing a bunch of city/suburb driving under 55mph (plenty of regenerative breaking, no passing people at 85mph, etc) then my max range in those conditions could get up to 375 miles (over 4 Mi/Kwh, car has a 91Kwh HVB). The opposite worst case of that would be a cold winter day where I'm driving for hours and hours on a high speed interstate road going 80+mph in zero traffic.  I'd be lucky to get 225 miles if it was really cold out.  As sold the car states a max range of 277 miles i think but since it's been a mild summer and I don't drive long distances often, my personal max range floats around in the 290 - 310 mile range.
