### ISSUE TITLE
fordpass_ignitionStatus sensor doesn't seem to be working properly

### ISSUE THREAD

**Issue by jwinston100** [itchannel/fordpass-ha#376]
I have an automation which uses the fordpass_ignitionstatus sensor changing to Off as a trigger to close my driveway gate if the car is also at home. After Fordpass screwed up their API and the integration had to be updated, this trigger stopped working. It would never trigger even though I saw in the history fordpass_ignitionstatus did change from On to Off. Here is the trigger for the automation:

```
trigger:
  - platform: state
    entity_id:
      - sensor.fordpass_ignitionstatus
    id: ignitionStatus changed to Off trigger
    to: "Off"
```

So I made a dummy automation for testing/debugging to see if any changes to fordpass_ignitionstatus would trigger anything:

```
trigger:
  - platform: state
    entity_id: sensor.fordpass_ignitionstatus
action:
  - service: notify.mobile_app_my_phone
    data_template:
      title: FordPass Ignition Status changed.
      message: >-
        Changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state
        }}
```

With this, I very frequently (whenever the status was refreshed) got notifications "Changed from On to On" if the car was running or "Changed from Off to Off" if the car wasn't and once "Changed from On to Off" when the engine turned off and "Changed from Off to On" when it turned on, but still the first automation would not be triggered ever.

Any thoughts as to what is going on or how to further debug this? Is there some issue with this sensor? Thanks.

**Comment by SquidBytes** [comment]
Just from glancing at this on my phone

> trigger:
  - platform: state
    entity_id:
      - sensor.fordpass_ignitionstatus
    id: ignitionStatus changed to Off trigger
    to: "Off"

I believe the value is all caps now as "OFF" I don't know HA well enough to know if that will impact it, but that could be an issue.

**Comment by jwinston100** [comment]
Thanks, but I've tried all caps, lower case, title case. It is case-insensitive.

**Comment by itchannel** [comment]
> trigger:
>   - platform: state
>     entity_id:
>       - sensor.fordpass_ignitionstatus
>     id: ignitionStatus changed to Off trigger
>     to: "Off"

Which version of this intergration are you running 1.57 or 1.58 beta 1 as the status changes "from on to on" could be caused by the API going unavailable which 1.58 fixes. 

The other issue or your automation not firing all try it on my dev instance and report back

**Comment by itchannel** [comment]
```
id: '1697600568268'
alias: New Automation
description: ''
trigger:
  - platform: state
    entity_id:
      - sensor.fordpass_ignitionstatus
    from: 'OFF'
    to: 'ON'
  - platform: state
    entity_id:
      - sensor.fordpass_ignitionstatus
    from: 'ON'
    to: 'OFF'
condition: []
action:
  - service: notify.persistent_notification
    data:
      message: Car has changed to {{trigger.to_state.state}}
mode: single
```

This works for me fine.
