### ISSUE TITLE
Issue with the attributes in the windowposition

### ISSUE THREAD

**Issue by max-github-mjhodgson-com** [itchannel/fordpass-ha#405]
I am seeing some non-window data in the attributes for windowposition:

```
DRIVER: 
updateTime: '2023-10-23T06:59:19Z'
oemCorrelationId: '74972'
value:
  doubleRange:
    lowerBound: 0
    upperBound: 0
vehicleWindow: UNSPECIFIED_FRONT
vehicleOccupantRole: DRIVER
vehicleSide: DRIVER

icon: mdi:car-door
friendly_name: FocusST Window Status
```

The "oemCorrelationId" is my odomter reading.
