### ISSUE TITLE
Car engine feedback feature?

### ISSUE THREAD

**Issue by doronazl** [itchannel/fordpass-ha#423]
When remote starting the engine from the ford app, once car started it shows a pop up message telling you if it started successfully or not.
Anyway to embed this into the integration? Currently if i start the car using the switch, it would take a while until the state updates in the sensors, minutes at least, sometimes 10 15 min.
Anyway to simulate what the ford app doing?

**Comment by SquidBytes** [comment]
I'm not experienced enough with HomeAssistant to know if there is a way to have a popup.

We do currently have a sensor called `fordpass_remoteStartStatus` which returns the status, and countdown value.

I would imagine your best bet to do something similar would be to setup an automation that if you trigger your ignition switch - you wait a few seconds then call `fordpass_refresh_status` to manually refresh the info, so its new information.

Depending on how you use the remote start switch, it could be in a conditional card - which would then display more information for you similar to a "pop up".

Here is a quick example I tried out.

```
type: entities
entities:
  - entity: switch.fordpass_ignition_switch
  - type: conditional
    conditions:
      - entity: switch.fordpass_ignition_switch
        state: 'on'
    row:
      entity: sensor.fordpass_remotestartstatus
      name: Remote Start Status
  - type: conditional
    conditions:
      - entity: switch.fordpass_ignition_switch
        state: 'on'
    row:
      type: attribute
      entity: sensor.fordpass_remotestartstatus
      attribute: Countdown
      name: Countdown Time
```

As I typed this I realized that I _believe_ the ignition switch in the integration does trigger a refresh, so it should be updated upon success.

You could also go a different automation route and send your phone a notification upon the state of `fordpass_remotestartstatus` turning to "Active"
