### ISSUE TITLE
in evcc.io they have an integration with Ford using an api id and token generated in  https://developer.ford.com

### ISSUE THREAD

**Issue by scruysberghs** [itchannel/fordpass-ha#559]
Below are the config options to get the car integrated in evcc.io:
```
Ford

vehicles:
  - name: my_car
    type: template
    template: ford-connect
    title: # Will be displayed in the user interface (optional)
    capacity: 50 # Battery capacity in kWh (optional)
    clientid: # Setup at https://developer.ford.com
    clientsecret: # Setup at https://developer.ford.com
    accessToken:
    refreshToken:
    vin: WF0FXX... # Required if you own multiple vehicles of the same brand (optional)
    icon: car # Icon as shown in user interface (optional)
    phases: 3 # The maximum number of phases which can be used (optional)
    mode: # Possible values are Off, Now, MinPV and PV, or empty if none should be set (optional)
    minCurrent: 6 # The minimum amperage per connected phase with which the car should be charged (optional)
    maxCurrent: 16 # The maximum amperage per connected phase with which the car shuold be charged (optional)
    identifiers: # Mostly this can be added later, see: https://docs.evcc.io/en/docs/features/vehicle (optional)
    priority: # Priority of the loadpoint or vehicle in relation to other loadpoints or vehicles for allocating pv energy (optional)
    cache: 15m # Time interval with when data should be reloaded from the vehicle (optional)
```
Reading all the issues with login etc here isn't this an option for this integration?
