### ISSUE TITLE
Continuously switching all entities from available to unavailable

### ISSUE THREAD

**Issue by Markw27348** [itchannel/fordpass-ha#568]
All entities under vehicle device are switching back and forth from the correct status to unavailable. Sometimes every few minutes and then in the meantime they are listed as unavailable, and sometimes every second. Version 1.70.

**Comment by zdietzen** [comment]
Ive noticed the same issues, mine are in 15min intervals it seems, where you can access the data and then 15min its unavailable. I believe this is Fordpass in the vehicle going to sleep to save battery. But this creates a huge issue because when things are unavailable I can't start/lock/unlock the vehicle. This breaks all my automations. Since sometimes the vehicle can be accessed and sometimes it can't be. Im thinking this is a ford issue. I wonder if there is a way to change settings on you vehicle to not put it in standby like this.

**Comment by affer** [comment]
<img width="1461" alt="Image" src="https://github.com/user-attachments/assets/e5e52ace-dd76-429d-86ca-8691e6ba15f4" />

same here - i tried changing time between update - still available/unavailable.

**Comment by zdietzen** [comment]
Thats pretty much how mine is. It's consistent though, so it makes me think this is set by Ford to prevent battery drain. To bad there isn't a way to set what hours 
 to disable the timeout. I love having my vehicle start automatically for me every morning and before work ends in the winter.  

<img width="550" alt="Image" src="https://github.com/user-attachments/assets/4e84cf33-6ba4-4bda-bc26-079d2d9ca6f3" />

**Comment by larryo108** [comment]
Have a look at [the thread for issue 530](https://github.com/itchannel/fordpass-ha/issues/530). There is a fix that has been working for me for months.

**Comment by zdietzen** [comment]
Thanks that thread helped! 

Going into FordPass config, setting the poll rate to 18000000 (something extreme), and then creating a manual script to update the fordpass data sort of works for me! 

I notice I get Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) when I run the script to refresh the Fordpass data sometimes. This usually only happens on the first attempt after it sits for a while without interaction.

It also happens sometimes if I attempt to lock/unlock or remote start from HA. I will get Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) then I can hit the button/action again and it will work the second time.

I am trying a little workaround by running the FordPass refresh script which runs twice, and I'm also running the FordPass refresh script just before I run my car start automation. I'm hoping this will get things working. 

Here is my yaml for starting my car in the morning-

Here is my FordPass Update script that calls the refresh and poll twice in case the error happens the first time-

```
alias: Update FordPass
sequence:
  - repeat:
      count: 2  # Try up to 2 times (first attempt + retry)
      sequence:
        - action: fordpass.refresh_status
          metadata: {}
          data: {}
        - delay:
            hours: 0
            minutes: 0
            seconds: 2
            milliseconds: 0
        - action: fordpass.poll_api
          metadata: {}
          data: {}
description: >-
  Manually update FordPass data by running the sequence twice in case the first
  attempt fails.
mode: single
```


```
alias: Ford F-150 Morning Auto Start
description: Starts Ford F-150 in the morning based on temperature and kitchen presence
triggers:
  - trigger: time
    at: "07:40:00"
conditions:
  - condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: weather.forecast_home
            attribute: temperature
            below: 45
          - condition: numeric_state
            entity_id: weather.forecast_home
            attribute: temperature
            above: 85
      - condition: state
        entity_id: binary_sensor.kitchen_presence_sensor_occupancy
        state: "on"
actions:
  - action: script.update_fordpass
    data: {}
    continue_on_error: true
  - delay:
      seconds: 7
  - action: lock.lock
    target:
      entity_id: lock.fordpass_doorlock
    data: {}
  - delay:
      seconds: 1
  - action: switch.turn_on
    target:
      entity_id: switch.truck_ignition
    data: {}
mode: single
```


<img width="944" alt="Image" src="https://github.com/user-attachments/assets/57d08747-0c46-4d35-93e8-548fca7be1ef" />
