### ISSUE TITLE
Kpa instead of PSI when UoM Metric is selected

### ISSUE THREAD

**Issue by degrashopper** [itchannel/fordpass-ha#66]
When you select the UoM "metric". You should also see the tire pressure in kilopascal. Kilopascal is the standard metric unit for pressure. 

The api sends the pressure data allready in kilopascal so you don't have to convert them when metric is selected.

**Comment by itchannel** [comment]
I'll have to have a think about how to implement this as I prefer it to read in "PSI" for metric hence why it does it :) 

However I can look at adding an individual option potentially if people would prefer it matching correctly.

**Comment by degrashopper** [comment]
Please change in sensor.py line 120 with the following additional if statement for emperial or metric return.

>            elif self.sensor == "tirePressure":
>                if self.coordinator.data["TPMS"] != None:
>                    if self.options[CONF_UNIT] == "imperial":
>                        return {
>                            "leftFrontTirePressure": round(
>                                float(
>                                    self.coordinator.data["TPMS"]["leftFrontTirePressure"][
>                                        "value"
>                                    ]
>                                    or 0
>                                )
>                                * 0.1450377377
>                            ),
>                            "rightFrontTirePressure": round(
>                                float(
>                                    self.coordinator.data["TPMS"]["rightFrontTirePressure"][
>                                        "value"
>                                    ]
>                                    or 0
>                                )
>                                * 0.1450377377
>                            ),
>                            "outerLeftRearTirePressure": round(
>                                float(
>                                    self.coordinator.data["TPMS"][
>                                        "outerLeftRearTirePressure"
>                                    ]["value"]
>                                    or 0
>                                )
>                                * 0.1450377377
>                            ),
>                            "outerRightRearTirePressure": round(
>                                float(
>                                    self.coordinator.data["TPMS"][
>                                        "outerRightRearTirePressure"
>                                    ]["value"]
>                                    or 0
>                                )
>                                * 0.1450377377
>                            ),
>                        }
>                    else:
>                        return {
>                            "leftFrontTirePressure": round(
>                                float(
>                                    self.coordinator.data["TPMS"]["leftFrontTirePressure"][
>                                        "value"
>                                    ]
>                                    or 0
>                                )
>                            ),
>                            "rightFrontTirePressure": round(
>                                float(
>                                    self.coordinator.data["TPMS"]["rightFrontTirePressure"][
>                                        "value"
>                                    ]
>                                    or 0
>                                )
>                            ),
>                            "outerLeftRearTirePressure": round(
>                                float(
>                                    self.coordinator.data["TPMS"][
>                                        "outerLeftRearTirePressure"
>                                    ]["value"]
>                                    or 0
>                                )
>                            ),
>                            "outerRightRearTirePressure": round(
>                                float(
>                                    self.coordinator.data["TPMS"][
>                                        "outerRightRearTirePressure"
>                                    ]["value"]
>                                    or 0
>                                )
>                            ),
>                        }
>                return None

**Comment by itchannel** [comment]
This has been implemented in #72

**Comment by MartyTremblay** [comment]
For those who wish to keep units in Psi but live in a metric world (aka Canada), this is the template I use:
`````
platform: template                                                                                                                                            
sensors:                                                                                                                                                      
  fordpass_tire_pressure_left_front:                                                                                                                          
    friendly_name: "Left Front Tire Pressure"                                                                                                      
    unit_of_measurement: 'psi'                                                                                                                                
    value_template: "{{ (state_attr('sensor.fordpass_tirepressure', 'leftFrontTirePressure') * 0.1450377377) | round }}"                                      
                                                                                                                                                              
  fordpass_tire_pressure_right_front:                                                                                                                         
    friendly_name: "Right Front Tire Pressure"                                                                                                     
    unit_of_measurement: 'psi'                                                                                                                                
    value_template: "{{ (state_attr('sensor.fordpass_tirepressure', 'rightFrontTirePressure') * 0.1450377377) | round }}"                                     
                                                                                                                                                              
  fordpass_tire_pressure_left_rear:                                                                                                                           
    friendly_name: "Left Rear Tire Pressure"                                                                                                       
    unit_of_measurement: 'psi'                                                                                                                                
    value_template: "{{ (state_attr('sensor.fordpass_tirepressure', 'outerLeftRearTirePressure') * 0.1450377377) | round }}"                                  
                                                                                                                                                              
  fordpass_tire_pressure_right_rear:                                                                                                                          
    friendly_name: "Right Rear Tire Pressure"                                                                                                      
    unit_of_measurement: 'psi'                                                                                                                                
    value_template: "{{ (state_attr('sensor.fordpass_tirepressure', 'outerRightRearTirePressure') * 0.1450377377) | round }}"
```
