### ISSUE TITLE
Battery Logic

### ISSUE THREAD

**Issue by paulgbrichardson** [itchannel/fordpass-ha#88]
The battery sensor is always STATUS_LOW, but I have a voltage of 13...  I updated it manually to STATUS_GOOD but the next update from Ford set it back to Low.
I have done ~10 hours of driving over the last three days and either I have a dodgy battery (maybe?) or the logic for the battery sensor isn't quite right. 

I did get a low battery alert from Ford a while back as the car was not used due to local lockdowns, but it has been driven a lot since then.

**Comment by itchannel** [comment]
So mine reads as a voltage of 12v and STATUS_GOOD. The status value is set by the ford API so I can only think that there might be something wrong with your battery or it's a little wobbly with your version of car. 

Do you have any alerts or messages in the Ford app?

This is what mine looks like 

![image](https://user-images.githubusercontent.com/5840973/111378616-cbd46e80-86ed-11eb-8c31-bd16a71380a9.png)

**Comment by denperss** [comment]
How can i add the battery voltage instead of "STATUS_GOOD" ?

**Comment by paulgbrichardson** [comment]
> How can i add the battery voltage instead of "STATUS_GOOD" ?

Its an attribute of the battery sensor.  If you want it as it's own sensor then create a template sensor - 

```
kettle_temp:
  friendly_name: "Car Voltage"
  value_template: "{{state_attr('sensor.fordpass_battery', 'Battery Voltage') }}"
  unit_of_measurement: "Volts"
```
